name: CI Workflow
on:
  push: # Trigger f체r Pushes
    branches: # Branch-Filter
      - main
      - develop
    tags: # Tag-Filter
      - "v*"
    paths: # Nur wenn bestimmte Dateien ge채ndert werden
      - "src/**"
      - "docs/**"
    paths-ignore: # Dateien/Ordner ignorieren
      - "README.md"

  pull_request: # Trigger f체r PRs
    branches: # Zielbranch des PR
      - main
      - develop
    paths:
      - "src/**"
    paths-ignore:
      - "docs/**"
    types: # PR Events
      - opened
      - synchronize # z.B. wenn neue Commits gepushed werden
      - reopened
      - closed # z.B. f체r Cleanup oder Tests nach Merge

  workflow_dispatch: # Manueller Trigger
    inputs: # Mit Input-Parametern
      environment:
        description: "Env name"
        required: true
        default: "staging"

  schedule: # Cron-Jobs
    - cron: "0 0 * * 1" # minute hour month_day month week_day

  release:
    types:
      - published
      - created
      - edited
      - prereleased
      - released

  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
